services:

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "2001:2001"
    depends_on:
      - db
      - discovery-service

  theatre-service:
    build:
      context: ./theatre-service
      dockerfile: Dockerfile
    ports:
      - "2002:2002"
    depends_on:
      - db
      - discovery-service

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "2004:2004"
    environment:
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
    depends_on:
      - db
      - discovery-service

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ticket_booking_db:/var/lib/mysql

volumes:
  ticket_booking_db:
