services:

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "2001:2001"
    depends_on:
      - db

  theatre-service:
    build:
      context: ./theatre-service
      dockerfile: Dockerfile
    ports:
      - "2002:2002"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookingDb
    ports:
      - "5432:5432"
    volumes:
      - ticket_booking_db:/var/lib/postgresql/data

volumes:
  ticket_booking_db: