spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schema=bookingDb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
  instance:
    prefer-ip-address: true
