spring:
  application:
    name: theatre-service
  graphql:
    schema:
      locations: classpath:/graphql
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
  datasource:
    url: jdbc:postgresql://db:5432/bookingDb
    username: root
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true

server:
  port: 2002

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
  instance:
    prefer-ip-address: true

